### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by johnste** [hundredrabbits/Left#10]
What is the intended license for Left? I would like to help out fixing bugs, etc, but without one I really can't.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

https://help.github.com/articles/licensing-a-repository/

**Comment by neauoire** [comment]
My mistake :) Added a license.

**Comment by johnste** [comment]
Usually, the license is added to the root of the project. It might be easier to find it that way. 
Anyway, looks good, thanks!
