### ISSUE TITLE
"Hide" and "Fullscreen" don't work on macOS

### ISSUE THREAD

**Issue by frozenpandaman** [hundredrabbits/Left#108]
Nothing happens when navigating to Left > Hide or pressing Cmd-H. The same is true for Left > Fullscreen / Cmd-F.

**Comment by neauoire** [comment]
Good catch :) Repaired!

**Comment by frozenpandaman** [comment]
Yay, thanks! :)

**Comment by frozenpandaman** [comment]
@neauoire At least on Mac, I noticed that it actually just hides the window (as if changing the opacity to 0%, and then pressing it again changes it back to 100%) instead of truly hiding the *application*, i.e. the application can still be active (showing in the status bar up top) even with the window invisible. The behavior I'd expect to see when pressing Cmd+H can be achieved by right clicking on Left in the dock and choosing "Hide".

Could this be fixed? I'd make a PR myself but I'm not familiar with Electron.
