### ISSUE TITLE
Quit & Close File do nothing on a file with unsaved changes

### ISSUE THREAD

**Issue by frozenpandaman** [hundredrabbits/Left#109]
Ideally, it should display a popup asking "There are unsaved changes in filename.txt. Are you sure you want to close it?" or something to that effect. Right now it does nothing. When there are no modifications compared to the last-saved version of the file, then it works as expected.

(Maybe this is intentional, because Force Close is also an option… but this behavior is unexpected and different than that of all other applications I use.)

**Comment by frozenpandaman** [comment]
I don't seem to be able to Quit (Cmd+Q) either. It seems like this is what's broken: https://github.com/hundredrabbits/Left/issues/50#issuecomment-362675335

**Comment by neauoire** [comment]
I'll have a look :)

**Comment by alisonmonteiro** [comment]
Hey 👋 

Is it related in any way with #113?

**Comment by neauoire** [comment]
I think it was yeah, the error was stopping the save from occurring!

**Comment by alisonmonteiro** [comment]
@neauoire nice. It's fixed 🎉
