### ISSUE TITLE
Clicking on the headers on the left should "bring" you there, right? It doesn't do anything for me.

### ISSUE THREAD

**Issue by noacubestudio** [hundredrabbits/Left#11]
I'm on Windows 10

**Comment by ubiko** [comment]
Fix for it in the PR, here's the commit:
https://github.com/hundredrabbits/Left/pull/12/commits/5f0e430fb0b05e29f28bd9a0adc2a2e5ba154523

**Comment by neauoire** [comment]
Pushed in build 9 :)

**Comment by neauoire** [comment]
Also, you can use square brackets to jump from one marker to the other.
