### ISSUE TITLE
Next File keyboard shortcut doesn't work on MacOS

### ISSUE THREAD

**Issue by achou11** [hundredrabbits/Left#110]
Currently on `0.1.0`. Seems like the shortcut for going to the next file takes you to the next marker instead. Going to the previous file using the shortcut works fine though.

**Comment by jkarttunen** [comment]
Seems to work fine for me.(Using finnish keyboard)

**Comment by achou11** [comment]
Hmm maybe it's just my keyboard. I have a similar issue with the same keybinding on another electron app. I'll close this.
