### ISSUE TITLE
Packaging into executable

### ISSUE THREAD

**Issue by flber** [hundredrabbits/Left#128]
Hopefully this is something obvious that I'm just missing or don't know how to do, but I haven't found any instruction in the readme for how to package Left into an executable file, like that which can be downloaded from itch.io. Am I missing something obvious or is this just something more involved that I should try and figure out on my own?
Thanks for the help!

**Comment by neauoire** [comment]
[This](https://github.com/hundredrabbits/Left/blob/master/desktop/package.json#L13) should work :)

Let me know!

**Comment by flber** [comment]
That works great, thank you! One thing I might change is that it creates the folder in `~\Documents\Left-win32-x64`, which would be good, except instead of putting it in a folder called Documents which is in the home directory, it creates a folder called `~` in the desktop folder and then continues from there.

**Comment by neauoire** [comment]
This is the script that is automated during my pushing builds to itchio, I should make another one for general use.

**Comment by flber** [comment]
Ah, got it. Thank you for your help!

**Comment by neauoire** [comment]
Have fun!
