### ISSUE TITLE
Cant create new document

### ISSUE THREAD

**Issue by iltimasd** [hundredrabbits/Left#13]

**Comment by neauoire** [comment]
huh? what do you mean.

**Comment by iltimasd** [comment]
Cant figure out a way to start a new document. 

I guess besides selecting all and deleting.

**Comment by neauoire** [comment]
Right, there is only ever one working document at once.
I haven't found a clever way to manage multiple documents.
You can drag a text file on Left if you just want to work from some other project.

**Comment by neauoire** [comment]
`ctrl+n` now clears the content :)

**Comment by iltimasd** [comment]
Awesome!
