### ISSUE TITLE
Feature: Autosave while typing 

### ISSUE THREAD

**Issue by aswinmohanme** [hundredrabbits/Left#131]
I really really love the minimalistic aesthetic of Left, and love writing on it.  It would be really awesome if there was toggle to autosave as I type the text so I no longer need to remember to save it. I could whip it up write my hearts content and then turn it off without any more thought.

**Comment by doxanthropos** [comment]
Just to add my two cents on autosave:
using autosave can be as destructive as not using it.
When you have no versioning, which would probably need way to much extra code for a program that is supposed to be minimalist, you can accidentally delete the contents of your file, (for example while typing fast, hitting CTRL + a and typing something else after that) and then have autosave save this state, which will also delete your work as effectively as not having it saved.
So when the goal is not to loose your work by accident, autosave removes one way of loosing your work, but introduces another one.

**Comment by aswinmohanme** [comment]
Yes and you could use Ctrl-z to undo the action ?

**Comment by neauoire** [comment]
I'm not keep on implementing this, I've ruined hours of work with some other tool that quietly saved and then suddenly(also quietly) didn't. Sorry
