### ISSUE TITLE
Running on Debian

### ISSUE THREAD

**Issue by flber** [hundredrabbits/Left#134]
This issue could very easily be the fault of my inexperience with linux, but running `npm run build_linux` on my debian computer results in the folder "Left-linux-x64" being created (good), but without any actual executable (bad). I'm not really sure what to do here, so any help or suggestions would be appreciated

**Comment by neauoire** [comment]
if you do `npm start` does it launch?

**Comment by flber** [comment]
It fails with the error `The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/ben/Documents/Left/desktop/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755`

Looking around, I fixed this by running
`sudo chown root chrome-sandbox`
`sudo chmod 4755 chrome-sandbox`

It just seems to be an issue with electron, and based on [this](https://github.com/electron/electron/issues/17972) issue, that fix is sort of the best method for now.
