### ISSUE TITLE
Project View, open folder

### ISSUE THREAD

**Issue by magoz** [hundredrabbits/Left#16]
- Add keyboard sounds when you type. It helps to focus. A good example is [Ommwriter](https://ommwriter.com/experience-test/).
- Add the option of playing some background sounds. Maybe some of your songs? It also helps focus, but I'm sure it's not for everyone, so having an option to enable/disable will be necessary. Same as the keyboard sounds.
- Add Finder/Dropbox integration, so you can drag a whole folder and find all your documents in the sidebar. I like how Ulysses does it. Perhaps you can add the tree of files at the bottom of the sidebar? It would be very convenient to switch between files.
- Markdown support. I'm aware it's not compatible with your current syntax (markers vs h1 and h2), but maybe could be a way to make it work? Markdown is super useful!
- Export options. Export file as formatted html/rich text. If you consider the Markdown support it will be useful to be able to export it as a formatted file.

**Comment by neauoire** [comment]
AH! Well you're going to be happy to know that project mode(drag folders, etc..) is almost ready :3
I'll see what I can do for audio. Thanks for the idea!

**Comment by magoz** [comment]
Wow, thanks @neauoire !! I've added more suggestions, I accidentally published my comment when I was writing it.
Thanks again for your work, I've just become an Engineer patron. Happy to support! :-)

**Comment by neauoire** [comment]
As for templating stuff, Rekka(for whom I'm currently building this atm), will soon need formatting options to render her novel into a formatted PDF file. My plan is to add templating stuff explicitly for books, so page breaks and so on.

More on that, very soon :)

**Comment by insanity54** [comment]
+1 on the Markdown support.

**Comment by vitordino** [comment]
I understand that Left was build to fill the gap that most markdown editors fail — on printed matter and extended formatting options.

But I still see advantages on using something, at least markdown compatible.
There are some extended markdown syntaxes, for example used in [iA Writer](https://ia.net/writer/) + external templating, that thinks on print+digital documents output.

So I believe that, maybe, there is a solution to both problems. (adopting markdown compatible + a nice/custom document output)

**Comment by neauoire** [comment]
That's the plan, for the release of our upcoming book I will need to have Left support templating options for print and output preview. At the moment I haven't spent that much time implementing rich text preview within the editor, I rather prefer Left to remain a basic text editor for now.

**Comment by neauoire** [comment]
Implemented `open multiple files`!
