### ISSUE TITLE
Text scaling

### ISSUE THREAD

**Issue by benjamin-rood** [hundredrabbits/Left#18]
My main suggestion:
* Text scaling with <kbd>ctrl</kbd> / <kbd>cmd</kbd> <kbd>+</kbd> / <kbd>-</kbd> (as per web browsers)

I'm afraid my eyesight is failing me somewhat, and I also find it much healthier to work with the display as far from my face as is possible.

It's a beautifully simple concept, don't go for feature bloat, keep it opinionated and focused. The <kbd>#</kbd> syntax for markers is very nice. The <kbd>tab</kbd> to cycle through synonyms feature is lovely.

**Comment by neauoire** [comment]
It's up :)
