### ISSUE TITLE
New file, Save overwrites previous file.

### ISSUE THREAD

**Issue by benjamin-rood** [hundredrabbits/Left#19]
If I have been working on file `A`, then create a new document `B` (<kbd>cmd</kbd><kbd>n</kbd>), if one then saves (<kbd>cmd</kbd><kbd>s</kbd>), rather than prompting for a new filepath for `B`, Left will use the filepath saved in the buffer (the filepath to `A`) and overwrite `A`.

It just overwrote the nice summary of Left I had written, so no harm done 😉 , but I should think this counts as _unexpected/incorrect behaviour_.

**Comment by neauoire** [comment]
You're right! That's a problem. I will fix this right away :)
(And add the increase/decrease font size feature, I'm also getting older).

**Comment by neauoire** [comment]
Fixed :) 
https://github.com/hundredrabbits/Left/commit/c31d43acbd34c1a0f065e65aef8f8d1ff719085e
