### ISSUE TITLE
Can't undo Ctrl+n

### ISSUE THREAD

**Issue by insanity54** [hundredrabbits/Left#20]
When I Ctrl+n, (Actually it's Command+n for me on OSX) it deletes everything in the editor. I can't Command+z (undo) to restore the text after said deletion. Is this the intended design or am I missing something? I'd hate to lose work if I accidentally hit Ctrl+n.

**Comment by neauoire** [comment]
Added dialog warning :)
https://twitter.com/hundredrabbits/status/912064737004855296
