### ISSUE TITLE
Partial Emacs navigation promotes Ctrl+n presses

### ISSUE THREAD

**Issue by insanity54** [hundredrabbits/Left#30]
One thing I've noticed is that the editor has partial Emacs navigation keybindings. The bindings in Emacs are as follows--

Ctrl+b moves the cursor backward one character (back)
Ctrl+f moves the cursor forward one character (forward)
Ctrl+p moves the cursor up one character (previous)
Ctrl+n moves the cursor down one character (next)

Ctrl+n is something very different in Left. It deletes all text and starts over with a fresh document.

I think the Emacs keybindings in Left should exist 100%, or not at all, as the existence of the first three but not Ctrl+n has led me to pressing Ctrl+n when I intended to move down one line. Instead of moving down a a line, my document disappeared. I've since updated Left so I get the dialog box which confirms Ctrl+n, (#20, many thanks!) but my force of habit of using Emacs keybindings feels awkward when it's not all there.

**Comment by neauoire** [comment]
Your wish is my command, give me a day or two :)

**Comment by neauoire** [comment]
It's Up!
`ctrl n` will no longer ask to create a new file, be careful tho, `ctrl N` will.
Also added Operator Mode on `Escape`, to mimic Emacs further. You can press `Escape` and `45` to go_to line 45. Enjoy :) Let me know if you have any more suggestions.

**Comment by insanity54** [comment]
I was ready to use the arrow keys to navigate as to not interfere with the existing Ctrl+n binding but I like this solution _much_ better!

"You are a gentleman and a scholar"

I think the Escape button is a Vi/Vim thing rather than Emacs, but I think it feels pretty natural having that button bring up a menu.
