### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by rishiosaur** [hundredrabbits/Left#32]
You're probably going to see a lot of new contributors, because of Hacktober, so shouldn't we have a wiki for contributing?

**Comment by neauoire** [comment]
Sure!

**Comment by rishiosaur** [comment]
@neauoire It's a coding festival that helps open source! [hacktoberfest.digitalocean.com](hacktoberfest.digitalocean.com). Also, thanks! I'll try to contribute.
