### ISSUE TITLE
Wiki structure

### ISSUE THREAD

**Issue by ragekit** [hundredrabbits/Left#36]
I was looking for  wiki app for my phd research but nothing seems to fit the bill (a stylish app that does not go in the way) so I was thinking of upgrade left with basic wiki structure.

I'd like the thing to be automatic : parse a buncha text files and check their title, and all the words that match this title in the curent document are now links to that other doc.

What is everyone thinking ? It might go too far from left initial design purpose tho so I might just fork

**Comment by neauoire** [comment]
Well, your other comment is about media, which I'm not too keen on since I want to keep this a plain-text editor. My thought is that Left could have a built-in formatter/exporter. So medias would simply be markup, not unlike how GitHub does it. And then Left could have a `build/render` option that generates an exported file.

That being said, I think a wiki, multi-file management would be **PERFECT** with Left. I would love to have something like what you describe. I can help if you want to get the ball rolling on this.

**Comment by ragekit** [comment]
Im going to check on it on my free time (ahah ah arggh). Its going to be mainly about UI/UX things likes : we are going to need a config file now, for the "root" of the wiki/multifile thing. How to set it up etc.

I propose that if no root is set the app works like it is now, but if a root is set with a command, it build an index and use the link thing (maybe togglable with a command)

**Comment by neauoire** [comment]
No need, I think the way it could work simply is, 
- we allow for multiple files to be opened at once, 
- display them in the navigation, 
- and have a render option that parses all the open files into a wiki output.

What say you?

**Comment by Zaeche** [comment]
I think the wiki-structure idea is _brilliant_ (media are debatable but perhaps a markup compromise is fitting, as suggested earlier). 

If we're talking about opening multiple files--either via the navigation or through embedded links--wouldn't some form of tabs keep things tidy? A quick design that just came to mind (without fretting about implementation at this point): 

![left-screenie](https://user-images.githubusercontent.com/6967538/32473603-4b7167f8-c336-11e7-97e8-433f7e0d779e.PNG)

I feel this meshes nicely with neauoire's list above, if not too distracting? Too abstract?

**Comment by ragekit** [comment]
looks like a good solution. Youd open a folder instead of a file then ?

Wondering if caching some stuff would be good for lots of file but lets not overdesign now

**Comment by Garry-H** [comment]
@ragekit you could try zim personal wiki
