### ISSUE TITLE
Logo merges into taskbar background

### ISSUE THREAD

**Issue by adarshrao** [hundredrabbits/Left#38]
Logo of Left blends into the dark background of my taskbar making it difficult to identify the application at a glance.

![left_logo_merged](https://user-images.githubusercontent.com/8955545/33069091-5fd48b7c-ced9-11e7-9e54-09eff43f94d0.png)

Operating System : Windows 10
Default Theme

Not sure if this is the correct avenue to raise this issue, feel free to close the issue if it isn't. 

Thanks.

**Comment by neauoire** [comment]
That's a good point, Maybe I should put backgrounds behind the apps..

**Comment by neauoire** [comment]
Fixed :)
https://github.com/hundredrabbits/Left/commit/27df197d7ae68e650558e8f97bd270ac54396777
