### ISSUE TITLE
Save overwriting

### ISSUE THREAD

**Issue by Garry-H** [hundredrabbits/Left#39]
In windows
Using the reset then using the save hotkey does not prompt to save to a new file, and will overwrite everything in the last file. Learned this the hard way. Would be nice to have it prompt asking what file to save to after using the reset hotkey.

**Comment by Garry-H** [comment]
i tried the reset hotkey after I noticed I couldn't use ctrl+n to start a new file

**Comment by EduardoHi** [comment]
The new file shortcut is actually <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>n</kbd>

**Comment by neauoire** [comment]
I'll implement new file with prompt on ctrl+n, you're not the first to hit this problem.

**Comment by Garry-H** [comment]
I tried ctrl+shift+n as well, it doesn't seem to be working in the version I have. I downloaded mine from itch.io

**Comment by neauoire** [comment]
Fixed, the shortcut is back to ctrl+n, just pushed a new build :)
