### ISSUE TITLE
Stats of selected text

### ISSUE THREAD

**Issue by EduardoHi** [hundredrabbits/Left#40]
When text it's highlighted, it would be nice to display custom stats of that selection only, momentarily, until unselected again. What do you think about that ? It could be useful to know the info of a specific fragment of the text.

**Comment by neauoire** [comment]
Oh yeah! Gimme a day and it'll be up!

**Comment by neauoire** [comment]
It's up @EduardoHi!
https://twitter.com/hundredrabbits/status/935601458136850432

Thanks for the request, it's actually pretty useful.
