### ISSUE TITLE
Font resizing not working on win10

### ISSUE THREAD

**Issue by alpacanist** [hundredrabbits/Left#41]
Hi,
Font related stuff doesn't work at all on my laptop. I've tried `ctrl +` with and without selecting the text. Is it a bug or that I'm missing something? 

plus, I cannot quit the program without using `Alt+F4` on win10. If you could equip the app with an exit operator (like `:q` in vim), it would be much appreciated. 
Thanks.

**Comment by neauoire** [comment]
I'll implement `alt+f4`, and `:q`.
For the font, it's `ctrl+shift-/+`.
