### ISSUE TITLE
Theme does not change on typing ~ left.theme = THEME

### ISSUE THREAD

**Issue by ThePhantomGamer** [hundredrabbits/Left#42]
I am using the itch.io app, and i have tried typing it in the manner shown in the video and in the operator menu. Both do not work. I have also dragged each theme onto the editor and seen it functioning.

Please let me know how I can do this/help fix this?
Thanks.
(maybe there is a settings file I am not aware of?)

**Comment by neauoire** [comment]
You have the latest build?
What platform are you on?
You've dragged (one of these files)[https://github.com/hundredrabbits/Themes] onto the Left window and it does not change?

**Comment by ThePhantomGamer** [comment]
I am using the version from itch.io
Win10
I have dragged each one of them, they all change on drag.
However, the functionality in the video, where typing `~ left.theme = <theme>` does not work

**Comment by neauoire** [comment]
I won't bring that option back for the time being.

**Comment by ThePhantomGamer** [comment]
Ok thanks for looking at it.
