### ISSUE TITLE
Unsaved changes block

### ISSUE THREAD

**Issue by Ryokin** [hundredrabbits/Left#43]
Right now on Windows 10 if I create a new file by hitting the keyboard shortcut ctrl + n and want to open a file it prompts me to save the file even when it is empty and I don't want to (I could drag a file to override this though).

**Comment by neauoire** [comment]
Oh! Good point, fixing that right now :)

**Comment by Ryokin** [comment]
Oh and a quick question, how do actually add a tab without it auto completing words?

**Comment by neauoire** [comment]
That's a good point, I never tab anything, I use double-spaces for everything.
Which behaviour would work for you for inserting a tab?

**Comment by Ryokin** [comment]
Hard to say, I personally never use the auto complete function. Place it on ctrl + tab for now? Maybe someone has a better idea.

**Comment by neauoire** [comment]
I'll make it that shift+tab always tabs, and I'll add a toggle in the menu to activate/de-activate the auto-complete suggestions. Give me a few hours and I'll push an update.

**Comment by Ryokin** [comment]
Awesome, great work!

**Comment by neauoire** [comment]
I've pushed a new build.
It's a *tiny bit* experimental, give it a shot, let me know what you think :)

**Comment by neauoire** [comment]
If you're not building from source, and using the Itchio builds, make sure to download through the itch client so you automatically get the updates, and don't have to redownload the whole thing each time.

**Comment by neauoire** [comment]
Fixed with Project Mode.
