### ISSUE TITLE
PR: Icon doesn't match UI

### ISSUE THREAD

**Issue by amilajack** [hundredrabbits/Left#45]
Willing to suggest some better icons

**Comment by neauoire** [comment]
I'd love to see that! :)

**Comment by neauoire** [comment]
I was gonna use the new look with the black background and white strokes.
Is that what you had in mind? That icon is pretty old.

**Comment by neauoire** [comment]
Fixed :)
https://github.com/hundredrabbits/Left/commit/27df197d7ae68e650558e8f97bd270ac54396777

**Comment by amilajack** [comment]
The icon has rounded accents to it and I thought that doesn't match the sharpness of the UI. What does the new icon look like?

**Comment by neauoire** [comment]
![left black](https://user-images.githubusercontent.com/1455726/35536622-499d2256-05ac-11e8-9076-61edf7a3c4fd.jpg)

**Comment by amilajack** [comment]
Nice!

**Comment by neauoire** [comment]
It follows the rest of the ecosystem, as per:
<img width="885" alt="screen shot 2018-01-30 at 10 26 25 am" src="https://user-images.githubusercontent.com/1455726/35536641-589950f4-05ac-11e8-919d-7dda2f98e2ee.png">
