### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by jkantner** [hundredrabbits/Left#46]
Very nice text editor, but a few usability problems:

- Window can only be dragged from top left
- Documentation lacks explanation for the following commands:
  - Speed reader (K)
  - Line (A)
  - Arc (S)
  - Arc Rev (D)
  - Bezier (F)
  - Connect (Z)
  - Thicker (`}`)
  - Thinner (`{`)
  - Thicker +5 (`]`)
  - Thinner -5 (`[`)
  - Linecap (Y)
  - Mirror (Space)
  - Fill (G)
  - Tools (U)
  - Grid (H)
  - Control Points (J)
  - Expert Mode (:)

**Comment by neauoire** [comment]
Hi @jkantner :)
Could you tell me what platform you're using? I can drag the window from anywhere by holding any of the padded side on OSX. 

As for the docs, something happened last night and the Dotgrid docs seems to have been merged with the Left docs. I will fix this right away.

**Comment by neauoire** [comment]
I've just tested on linux and OS X and anywhere on the left side navigation can be used to drag the window as per design.

**Comment by jkantner** [comment]
I’m using macOS 10.13.2, and I expected to be able to drag the window around from anywhere in the title bar (despite it being blank) like any other app.

**Comment by neauoire** [comment]
I made the top of the window draggable :)
<img width="933" alt="screen shot 2018-01-31 at 9 08 52 am" src="https://user-images.githubusercontent.com/1455726/35589578-37369dbe-0669-11e8-900e-e039da23eec0.png">
