### ISSUE TITLE
Missing Spaces In Markers.

### ISSUE THREAD

**Issue by giliwawa** [hundredrabbits/Left#47]
Hi, I just started using the editor and I love it this. I noticed when placing markers that there is spaces missing :
 
![image](https://user-images.githubusercontent.com/7778248/35629617-5edc1fe8-069f-11e8-933c-391174ec28d9.png)

Adding a space after the marker characters (## | # | --) seems to fix it. I was wondering, is this the intended behaviour?

**Comment by neauoire** [comment]
Yep : )
