### ISSUE TITLE
Reader Mode not working on macOS 0.1.0 version

### ISSUE THREAD

**Issue by tomgenoni** [hundredrabbits/Left#48]
Really like the simplicity of Left. But not sure what Reader Mode is supposed to do, I assume render the Markdown nicely? The menu bar flickers momentarily but immediately returns to the authoring mode.

**Comment by neauoire** [comment]
That's a good point, I'll clarify what it does.
It's something I use when doing text review, to try it, select some text and press cmd+k. 
You'll see what it's for :) 

I'll add a warning when there is no text selected.

**Comment by tomgenoni** [comment]
ah, thank you. I see how it works now.

**Comment by neauoire** [comment]
Thanks for the tip 👍 
Pushed a new build that makes the reader's purpose more explicit!
