### ISSUE TITLE
Make some settings available

### ISSUE THREAD

**Issue by lajlev** [hundredrabbits/Left#49]
I miss following:

-  Set font
-  Custom keyboard shortcut for prev./next marker

**Comment by neauoire** [comment]
How would you like the UX for fonts to be handled? I was thinking of giving the option to use Rasmus' InterUI as non-fixed width font.

The prev/next markers are `CmdOrCtrl+]` and `CmdOrCtrl+[` as per documented [here](https://github.com/hundredrabbits/Left) and here:
<img width="455" alt="screen shot 2018-02-02 at 10 28 59 pm" src="https://user-images.githubusercontent.com/1455726/35726084-7d4cf518-0868-11e8-903e-b89fbf6bc546.png">

**Comment by lajlev** [comment]
I think you should build a simple setting modal triggered by `cmd + ,` Maybe cherry pick some fonts delicious fonts

The shortcuts for prev/next markers is hard on non-US keyboard (using a danish keyboard).

**Comment by neauoire** [comment]
What would be a good alternative for you, for the prev/next markers?

I think I've got an idea for the font, I will give it a shot in the morning, you can tell me what you think 👍

**Comment by lajlev** [comment]
Awesome. Quick response.


On 2 Feb 2018 at 10.43, Лu Лinveгa <notifications@github.com> wrote:


What would be a good alternative for you, for the prev/next markers?

I think I've got an idea for the font, I will give it a shot in the
morning, you can tell me what you think 👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hundredrabbits/Left/issues/49#issuecomment-362536797>,
or mute the thread

**Comment by neauoire** [comment]
I think this looks pretty good!

<img width="1279" alt="screen shot 2018-02-03 at 9 15 12 pm" src="https://user-images.githubusercontent.com/1455726/35765383-6d32ff14-0927-11e8-8897-adf8f29ff584.png">

**Comment by tw** [comment]
@neauoire I am considering implementing the ability to select a font - is there any preferences as to how you'd want it approached? If I did it what would need to happen to get it into the main repo.

**Comment by neauoire** [comment]
Well, I've started to thinker with this a bit but here's what I'm suggesting.
3 fonts, a selection of a mono, serif and sans serif. It has to work offline so the fonts needs to be embedded in the app, so within `media/fonts`. As @lajlev suggested, something like `cmd + ,` to cycle through them would be enough.

**Comment by tw** [comment]
@neauoire nice one thanks for the comment, my motivation for completing it was to add Inconsolata as a font.

I'm happy to add a selection of fonts, and then you can cycle through them via `cmd + ,` - Currently `cmd + ,` maps to open this repo on GitHub - is it OK to remove this or would you like me to move it to an alternate keybinding?
