### ISSUE TITLE
Close Icon Doesn't Work in Windows 10

### ISSUE THREAD

**Issue by lynnellemmanuel** [hundredrabbits/Left#5]
Hello. I've running the app in Windows 10 64-bit and would like to report that the Close button (right of maximize/minimize button) is not working.

**Comment by lynnellemmanuel** [comment]
Alt+F4, Right click at taskbar and Close Window, both doesn't work. I have to open Task Manager and have to end the task for Electron for it to close.

**Comment by johnste** [comment]
Similar issue on MacOS 10.12.5 - attempting to close the window with the close button in the window top does nothing. I can quit it with ⌘Q though.

**Comment by neauoire** [comment]
I will add alt+f4 for windows, I was on my way to remove the buttons entirely.
