### ISSUE TITLE
App close deletes current file content if unsaved

### ISSUE THREAD

**Issue by drecodeam** [hundredrabbits/Left#50]
Closing the app just deletes the content of app. Opening application again starts a new file from scratch. 

Either we can have a prompt asking user to save the file, or have an option of restoring the previous unsaved file.

**Comment by neauoire** [comment]
Oh! You're right, I will add a yes/no modal before closing when there has been file changes.

**Comment by neauoire** [comment]
Fixed :)
<img width="555" alt="screen shot 2018-02-03 at 8 01 33 am" src="https://user-images.githubusercontent.com/1455726/35750069-957aef50-08b8-11e8-8826-858746f29c73.png">
