### ISSUE TITLE
Undo not working for some operations

### ISSUE THREAD

**Issue by gonzalocasas** [hundredrabbits/Left#51]
The Undo support seems to have issues. Simple undo tests work, but doing trivial things like inserting tabs and spaces already make the undo feature trip.

OS: Windows 10.

**Comment by Redmega** [comment]
Not able to replicate on macOS 10.13.3

**Comment by gonzalocasas** [comment]
It seems to come down to Tab not being undone properly.

OS: Windows 10, Version 1709, Build 16299.125

### Two variants of the bug

#### Case 1
**Steps to reproduce**
- Open Left (leave the "Good morning" text in place")
- Press tab once
- Press Ctrl+Z
- **Nothing happens, no undo**

#### Case 2
**Steps to reproduce**
- Open Left (leave the "Good morning" text in place")
- Press space once
- Press tab once
- Press Ctrl+Z
- **The space is undone, but not the tab, and the cursor ends up in column 0 of the current line**

**Comment by Redmega** [comment]
I replicated on Windows 10. Tabs don't get undone!

On MacOS I noticed that it undid **all** sequential tabs with one undo action, so If I tabbed three times after some text and undid it would put the cursor back to where the text was. I figured this was intended but I now think it's just a related bug.

**Comment by Redmega** [comment]
If you:

1. go to the front of the good morning, 
2. tab
3. select all and delete
4. undo

you end up with your Good Morning text back, but with the tab in front of it!
