### ISSUE TITLE
Support bold and italic

### ISSUE THREAD

**Issue by gonzalocasas** [hundredrabbits/Left#52]
It would be nice to have bold and italics support using markdown, in a similar way Atom and Code have.

**Comment by Redmega** [comment]
> in a similar way Atom and Code

Atom and Code don't allow you to bold from within the text editor, I believe. If you're talking about the markdown preview they support, that's compiling (transpiling?) your written .md into markdown and showing it in the window. Not quite the same.

However, I believe bold can be implemented anyway.

@neauoire Do you feel like you should have to \*type\* asterisks around the word you want bolded, or should a `cmd/ctrl + b` toggle bold text? Or both? If asterisks, would the asterisks hide themselves? What do you think @gonzalocasas ? 

Which do you think would work best with the minimalistic control scheme?

**Comment by neauoire** [comment]
Ideally `cmd/ctrl + b` would append `*` before and after the selected word. I want left to always display all characters. It's a plain-text editor more than anything else.

**Comment by gonzalocasas** [comment]
> Atom and Code don't allow you to bold from within the text editor, I believe. 

They do, and it does not require compiling/transpiling+previews, it's inlined.

Atom:
![image](https://user-images.githubusercontent.com/933277/36012652-eaca065c-0d5f-11e8-9512-2c3479fc6df4.png)

Code:
![image](https://user-images.githubusercontent.com/933277/36012660-f8e59ae4-0d5f-11e8-81f0-e66a2ab54c84.png)

The shortcut is secondary imo, it does not add a lot of value.

**Comment by Redmega** [comment]
That depends on your syntax theme, as that's part of the syntax highlighting, and not technically the editor.

For example, the theme I'm using actually supports the bold and italics like yours, but my titles aren't bold.

In any case, thanks for showing me that, I never realized! I don't use it for markdown much outside of README's.

**Comment by gonzalocasas** [comment]
I don't recall exactly, but I think VS Code comes with these settings/syntax highlighting out of the box. Atom I probably customized, you're right.

**Comment by neauoire** [comment]
I will not add syntax highlight, or font styles to Left.
Sorry

**Comment by pacocoursey** [comment]
What if wrapping text with certain characters triggered a style being applied? The text would be still be stored as plain-text but it would show up as having styles.

For example:
```
This passage of text has a *bold* string.
```

When typing the asterisks around a bit of text, a `<span class="bold"></span>` could be applied. The file would still contain the plain text string.

`*text*` bold
`/text/` italics
`-text-` strikethrough
`_text_` underline

etc...

I believe [Bear Writer](https://bear.app/#features) does this.

**Comment by neauoire** [comment]
It's a slippery slope to getting asked to implement tables and images and other things.
I personally don't use Left to write markup text.

If you would like to try and implement bold, underline and italic, give it a shot.
There are some really good markup templating tools out there, I prefer to think of Left as for *just writing*.
