### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by Redmega** [hundredrabbits/Left#54]
This repo should have a contributing guide if there's anything you need or expect from user contributions! Semantic commit messages, code style, etc!

**Comment by neauoire** [comment]
I don't really expect anything in term of style, people can fix bugs as they like, I always go over the code to make it comply with the rest of the style. I don't merge a PR if I don't understand it. :) 
I'll write a CONTRIB file if things start to get out of hands.

**Comment by Redmega** [comment]
Sounds good @neauoire. Would you consider something like `prettier` or `xo` so that formatting isn't even up to the user anymore? you can have a `precommit` hook that runs the formatter of your choice.

**Comment by neauoire** [comment]
I prefer not, I'm still learning JS and my experience with Prettier has been less than excellent. I will implement at some point in the near future. It's on my list tho.

**Comment by Redmega** [comment]
Might I ask what issues you faced? I ran into some problems where it would mess up indentation on certain files as well, which is why I recommended `xo`. It just worked better for me for my use cases.

**Comment by Redmega** [comment]
In any case I'm excited to start contributing, I haven't worked with electron before so I'm looking forward to diving in!

**Comment by neauoire** [comment]
It messed up formatting on pretty large files, and it injects a lot of "apparent" changes to git commits that makes it harder for me to parse what is going on in the code in same instance. It also breaks my database format(see Oscean), but it's not present in this repo.

I'll be happy to help you get started if you have any question. The code is pretty simple.

**Comment by gryte** [comment]
I'm also interested. Any tips or online references for getting up to speed on electron development?

**Comment by neauoire** [comment]
Electron is really just a wrapper that turns a website into an app. So I'd just learn to make cool websites-like tools and wrap them up. The point is to make something that is cross-platform and easily deployable, and open source.
