### ISSUE TITLE
Not leaving a space after a # causes the space to be removed after the first word

### ISSUE THREAD

**Issue by Redmega** [hundredrabbits/Left#58]
<img width="401" alt="screen shot 2018-02-08 at 10 54 58 pm" src="https://user-images.githubusercontent.com/662951/36011131-5dc44006-0d23-11e8-9325-ddbde7cae6b6.png">

As you can see, not leaving a space inline after the `#` marker causes the space to be removed from after the first word in the sidebar.

**OS:** MacOS High Sierra 10.13.3
**Left:** ver70 on itch.io

**Comment by neauoire** [comment]
This is by design :) So people can still start lines this way, also this allows me(or anyone) to open `.rb` files and not having the whole comment printed in the sidebar :)

**Comment by neauoire** [comment]
Oh, I misread your issue at first.
I'll have a look :)

**Comment by Redmega** [comment]
If you haven't the time I can take a look tomorrow!

**Comment by neauoire** [comment]
Sure, if this is still unfixed tomorrow, give it a try : )

**Comment by neauoire** [comment]
Fixed :)

**Comment by Redmega** [comment]
Haha! No chance at all for me 💯

**Comment by neauoire** [comment]
I went ahead and fixed it as this will be refactored right now because there is a bit of code duplication.
