### ISSUE TITLE
Un-hiding Window on Windows 10 does not work

### ISSUE THREAD

**Issue by tomual** [hundredrabbits/Left#59]
There is an option to hide the window, but there appears to be no option to unhide the window.

Ctrl + H makes the window disappear, and pressing Ctrl + H again does not do anything.

**Comment by neauoire** [comment]
really? it works for me on OSX.
Could you make sure that you're not getting an error.
Press `cmd .`, then `cmd h`. 
Does it give you an error in the console?

**Comment by Redmega** [comment]
`cmd + h` is working to hide and unhide for me on MacOS High Sierra 10.13.3

**Comment by tomual** [comment]
It appears to be a bug for Windows 10 then - here is a GIF of it.

https://i.imgur.com/aAS22OJ.gif

1. Open Left
2. Ctrl + H to hide, Ctrl + H again - nothing happens
3. Alt + Tab to see list of current windows, Left is not there.
4. View task manager, where Left is still running

On Windows for Electron Apps (Slack, Discord) when the process is running, they show a task tray icon. Perhaps Left could do this.

Either that or disable Ctrl + H for Windows.

**Comment by Redmega** [comment]
> when the process is running, they usually show a task tray icon

I believe this is the best course of action for windows.

On macOS, Most windows lose focus when hidden so it doesn't make sense to unhide them. I think the unhide shortcut should just be removed entirely.

**Comment by neauoire** [comment]
I will disable hiding on windows entirely, it will simply minimize the window.
