### ISSUE TITLE
Saving doesn't work on MacOS

### ISSUE THREAD

**Issue by johnste** [hundredrabbits/Left#6]
When I press ctrl+s (or cmd+s) I get no save dialog, which I think is what is supposed to happen.

**Comment by tiJy** [comment]
I would like to add that even on Windows, it doesn't save when I press ctrl + s.

**Comment by camiloei** [comment]
weird... this is working for me right now. 

I'm on Mac OS sierra v 10.12.6

**Comment by gingerbeardman** [comment]
Not working for me macOS 10.12.6

how odd

**Comment by johnste** [comment]
Saving works when I run the application directly from source. That's weird.

**Comment by neauoire** [comment]
@gingerbeardman Does it say you have the latest build on the itchio client? I will have a look at this today :)

**Comment by gingerbeardman** [comment]
Could be the app is running from a randomised path of you don't move it after unzipping? 

http://lapcatsoftware.com/articles/app-translocation.html

> If you're running MacOS Sierra, it is important to move the app before running, otherwise, it will get translocated (the app will run from a randomized path and won't have access to the game data files).

**Comment by neauoire** [comment]
<img width="1280" alt="screen shot 2017-09-05 at 7 39 45 am" src="https://user-images.githubusercontent.com/1455726/30036181-723de262-920d-11e7-9522-1eaa4de78ad4.png">

On OS X, without moving the build from it's folder, pressing ctrl+s opens this dialog box.

**Comment by gingerbeardman** [comment]
Is that a binary that has his just been downloaded from github and unzipped? 

I'll try to reproduce asap

**Comment by neauoire** [comment]
Yeah, if you can use the electron script, let me know if it works for you :)
Otherwise I can get you a link to this build, to test it.

**Comment by gingerbeardman** [comment]
`Control+S` brings up the save as dialog
`Command+S` does not

**Comment by neauoire** [comment]
Added to v8
