### ISSUE TITLE
¿Tabs in Left? ¿Two Windows?

### ISSUE THREAD

**Issue by VictorIrix** [hundredrabbits/Left#60]
It would be a great option to have tabs or the possibility of opening several text editors. I am not sure if this should go here, but of course it is limiting the fact that only one window is available.

Congrats for the app.

**Comment by neauoire** [comment]
You can open multiple files at once in left. 
They are listed on the left alongside the markers, this is a sort of tab isn't?

<img width="995" alt="screen shot 2018-02-20 at 8 56 10 pm" src="https://user-images.githubusercontent.com/1455726/36412780-7fc294d0-1680-11e8-83e9-538e3da224b4.png">

**Comment by VictorIrix** [comment]
Yeeeeeeeeeeeepppp!!! Thanks @neauoire !! I don´t know the feature!
