### ISSUE TITLE
# is supposed to be showed on left?

### ISSUE THREAD

**Issue by 0xc00000404b** [hundredrabbits/Left#62]
When i do 
##Hello
 
The "#" is showed on left bar
![oof](https://user-images.githubusercontent.com/18698901/36897217-6cb98706-1df4-11e8-8b72-ae9e44e55679.png)

How i can change this to make left more like this
![preview](https://user-images.githubusercontent.com/18698901/36897223-755b86c0-1df4-11e8-8c67-7518df9dc73c.jpg)

I'm on windows10 btw

Sorry for the bad english, i'm russian

**Comment by neauoire** [comment]
Добавьте <space> между `#` и `словом`, like `# Hello`.
В `#headings` нет <tabs>.
хорошего дня!

**Comment by 0xc00000404b** [comment]
Спасибо, мой друг!
