### ISSUE TITLE
Auto complete and synonym suggestions not working on macOS

### ISSUE THREAD

**Issue by camiloei** [hundredrabbits/Left#7]
I'm not seeing any suggestions after setting active those features with the ~ Left. command

**Comment by gingerbeardman** [comment]
I'm seeing them. Seems to not work in the default text so make sure you clear it to start a new document. Also it says that the synonyms dict only contains ~12K words.

![screen shot 2017-09-04 at 15 08 02](https://user-images.githubusercontent.com/49612/30029864-e0d73916-9182-11e7-8d44-b30f3c4c5836.png)

**Comment by neauoire** [comment]
Can you double check? 
I'm running the same OS and build as you and I see them :)

**Comment by gingerbeardman** [comment]
Can I pick a synonym from the list or are they just to be read for inspiration?

**Comment by neauoire** [comment]
They could be click, I kindda like that idea :) Adding.

**Comment by neauoire** [comment]
Added in version 8 :)

**Comment by camiloei** [comment]
I made a build again with the latest version and everything seems to work fine!
