### ISSUE TITLE
There is no way to display menu bar on Windows

### ISSUE THREAD

**Issue by JakubValtar** [hundredrabbits/Left#70]
It's fine if you learn all the shortcuts, but not good for new users. Maybe you have some ideas how to make it available, like putting the app icon in the top left corner, which would pop up a context menu when clicked.

**Comment by neauoire** [comment]
I could add a splash screen with all the controls.

**Comment by JakubValtar** [comment]
Might work for some people. Maybe it's not that big of a problem after all. It's just nice to have access to all the functionality without remembering every last shortcut.

**Comment by neauoire** [comment]
The problem with a context menu is that I don't have it on OSX and cannot test it.
I would gladly merge a PR, but I don't tackle windows issues since I cannot test them.

**Comment by JakubValtar** [comment]
Ah, right. I might give it a shot later. Until then I'm gonna put the window frame back in my installation as an easy workaround.

**Comment by neauoire** [comment]
Oh, you have the menu bar if the window frame is on? Is there a way to display/hide the menu bar on a key press? Maybe something like `view > hide menu bar` could work well for Windows users who prefer to use the shortcuts?

**Comment by JakubValtar** [comment]
It is hidden, but it appears when you press left alt. Then it hides after you click back into the window or press alt again. I think this is standard behavior, e.g. Firefox does it too and left alt is has been used for focusing menu bar for ages.

It does not look great, but it is fine if you work fullscreen and use the menu only occasionally.

![screenshot 4](https://user-images.githubusercontent.com/3177098/38710239-969ffb18-3ebf-11e8-9e36-a588d3ecbba8.png)

**Comment by markhu** [comment]
Any progress on this? No fun re-reading the "splash" file to try to find the keystrokes.

**Comment by neauoire** [comment]
Fixed :)

**Comment by JakubValtar** [comment]
<3
