### ISSUE TITLE
Discard is right next to Save and has no confirmation and no undo

### ISSUE THREAD

**Issue by JakubValtar** [hundredrabbits/Left#71]
Feature request: Crtl+D instead of Crtl+S can vaporize hours of work, confirmation dialog or undo would be appreciated :)

**Comment by neauoire** [comment]
Oh, I'll add a modal!

**Comment by JakubValtar** [comment]
Sounds great, thanks :)

**Comment by neauoire** [comment]
Added in #fab5a9840527403e66d6e361a9fbd4554803b362

**Comment by JakubValtar** [comment]
Thanks, looks great! I sent a PR with some small fixes which should come in handy :)
