### ISSUE TITLE
Unexpected and incorrect behaviour 😩

### ISSUE THREAD

**Issue by gingerbeardman** [hundredrabbits/Left#8]
**Issues**
- suggestion for word when cursor is at end of word (completing the suggestion duplicates the final letter of word)
- word _keeps_ shows synonyms for the word _keep_, but the word _keeps_ has no synonyms?
- word suggestion appears when the cursor is in the middle of an already completed word
- suggestion for word before punctuation when cursor is positioned after punctuation (see left.mov)
- undo changes text elsewhere in the document than the text that has just been edited
- cursor position for suggestions, and cursor position for editing seem to differ at times? results in much strange behaviour

here I just step through document using the right cursor key: 
https://transfer.sh/mdF9R/left.mov 

in this one i do the same, and then try suggestions and undo:
https://transfer.sh/LFwNh/left2.mov
(both available for 14 days)

after encountering these i stopped testing.

**Comment by neauoire** [comment]
So basically:
- Turn off autocomplete when NOT at the end of a string.
- Support synonyms for plurals

- suggestion for word before punctuation when cursor is positioned after punctuation(gotcha!)
- undo changes text elsewhere in the document than the text that has just been edited(huh, weird)
- cursor position for suggestions, and cursor position for editing seem to differ at times? results in much strange behaviour(very huh, weird)

On it.

**Comment by neauoire** [comment]
I've pushed a new build with new behaviours for autocomplete suggestions :) I think it removes some of the weird stuff :) Let me know what you think!

**Comment by gingerbeardman** [comment]
mostly fixed.

using text

```
# Test

Testing.

happy
```

- cursor positioned between _#Test_ and _Testing_, press tab, the percentage changes though no tab is entered
- still some strangeness with synonyms whilst moving cursor back and forth across word _happy_ synonyms for _hap_ are triggered when cursor is like this happ|y and _happ_ when cursor is like this happy|, then pressing right one more time doesn't move the cursor (because we're at the end of the document) but it does update the synonyms to be of _happy_

https://transfer.sh/iOuXS/test.mov

**Comment by gingerbeardman** [comment]
another odd one

- launch
- position cursor after _word._
- press tab

- you get _word.s_

https://transfer.sh/qsqwx/s.mov

**Comment by gingerbeardman** [comment]
latest itch build (just downloaded 10:30AM 7th Sept)

```
# Test

words.

happy```

- cursor after _words._ gives suggestion _voice_ tab gives _words.voice_
- undo doesn't undo suggestion or synonym insert
- quitting app without saving/exporting does not save my text

that's all the time i have for testing, i'm sure there's more quirks (sorry)

**Comment by neauoire** [comment]
Fixed :)
