### ISSUE TITLE
Heading levels not displaying properly on windows 10

### ISSUE THREAD

**Issue by vikepic** [hundredrabbits/Left#80]
First of all, i love your software and your aesthetic.

Second of all, this happens with the itch.io build for windows 10 as of this day:

![capture](https://user-images.githubusercontent.com/17166671/40169245-dd461db0-59c5-11e8-9dde-5faa9a400f92.PNG)

As you can see, heading identation is messed up in the sidebar.

Thanks for your time.

**Comment by neauoire** [comment]
You're right, I'll have a look at this :)

**Comment by neauoire** [comment]
Should be working properly now?

**Comment by Arty2** [comment]
Unfortunately not, it persists. Anything I can do to help debug?

**Comment by neauoire** [comment]
If you can build the app from source, could you look at Navi.js? The EOL variable is declared in left.js and it specifies the linebreak type. I have no idea how win32 does linebreaks :( 

👁‍🗨

**Comment by vikepic** [comment]
> Unfortunately not, it persists. Anything I can do to help debug?

Same here.

![capture](https://user-images.githubusercontent.com/17166671/45416665-b98e9b00-b680-11e8-9ed8-099b2cb907ae.PNG)

**Comment by neauoire** [comment]
Damn, I need someone who can has a Windows machine and knows a bit of JS to help me debug this.
I cannot test/fix this one with my current linux setup.

**Comment by neauoire** [comment]
Fixed :)
