### ISSUE TITLE
Auto-complete stops after 3 characters?

### ISSUE THREAD

**Issue by mattdesl** [hundredrabbits/Left#81]
Hello, just downloaded the latest (v1.8.7) and noticed auto-complete is ignored if your word is longer than 3 characters. Is that intentional?

As soon as I type 'h' the technologists suggestion disappears:

<img width="285" alt="screen shot 2018-08-04 at 12 03 24 pm" src="https://user-images.githubusercontent.com/1383811/43675828-7852a81a-97b4-11e8-8803-4b4802c72757.png">

**Comment by neauoire** [comment]
<img width="406" alt="screen shot 2018-08-05 at 8 27 15 am" src="https://user-images.githubusercontent.com/1455726/43680229-63b54d24-9889-11e8-8454-9d2311ded4ec.png">

I don't seem to be having this issue. I'll investigate.

**Comment by neauoire** [comment]
I cannot replicate, but I've pushed a new build that adds the synonyms to the startup dict.
Could you have a look into the `dictionary.js` and see if you get suggestions?

**Comment by neauoire** [comment]
Shall I go ahead and close this?
