### ISSUE TITLE
Preserve Capitalization in Titles

### ISSUE THREAD

**Issue by mattdesl** [hundredrabbits/Left#82]
This is a small issue, but I noticed `text-transform: capitalize` is used in the CSS for the navigation. To me this seems a bit odd, and it would be better to preserve the capitalization the author intended.

https://github.com/hundredrabbits/Left/blob/8c8324aef36a8ae2c38930ad628340e2d0bb2651/desktop/sources/links/main.css#L10-L13

Here's an example of the problem:

<img width="436" alt="screen shot 2018-08-04 at 12 05 01 pm" src="https://user-images.githubusercontent.com/1383811/43675849-eddc4bf4-97b4-11e8-8bc0-428023832ee9.png">

**Comment by neauoire** [comment]
You're right!
Good point, fixed 👍
