### ISSUE TITLE
Request: Auto-refresh documents

### ISSUE THREAD

**Issue by Arty2** [hundredrabbits/Left#83]
Would it be possible to auto-refresh documents (or ask to save changes) if they open file
has been changed in a different editor while open in Left? It’s a standard feature in Sublime Text, Notepad++ and other editors. It's very useful if you need to switch between editors for good looking code notes.

Kudos on the great work on this!

**Comment by neauoire** [comment]
I'm looking into it, I haven't found a solution for this yet.
Stay tuned :)

**Comment by neauoire** [comment]
Foun a way to make this work :) 
Will push an update shortly.
