### ISSUE TITLE
Keyboard shortcuts suggestions

### ISSUE THREAD

**Issue by isRyven** [hundredrabbits/Left#90]
1) `<Ctrl+Enter>` should not fullscreen the window, `Alt+Enter` or `F11`  should be used instead (on Windows at least).
2) `<Ctrl+Enter>` is actually  supposed to set a newline from the current cursor position without dividing the line, like other text editors do.

As a side note, i have no idea what speed reader does ☹️.

**Comment by pacocoursey** [comment]
Can you elaborate on the desired behavior for `<Ctrl+Enter>`? On macOS pressing that keybind is equivalent to simply pressing `Enter`.

Speed reader mode automatically highlights text and outputs the current word at the bottom of the window in the same position. Having the words of a passage outputted at the same visual area allows for much quicker reading speed and comprehension. You don't have to move your eyes, and you generally don't internally say every word you read (I think it's called subvocalization).

Here's a [meme](https://i.kym-cdn.com/photos/images/original/001/334/923/c37.gif) of speed reading in action.

**Comment by neauoire** [comment]
We could make it so when you press speed reading without a selection. It automatically selects the current line? 

👁‍🗨

**Comment by neauoire** [comment]
As for <c-enter>, The way I understand it, is that it goes to the end of the line before adding a linebreak, this way, if you’re in the middle of a sentence, it doesn’t break it, but still adds a new line.

👁‍🗨

**Comment by isRyven** [comment]
Thanks for your response guys.

Yeah as @neauoire said, it does a newline without breaking the current line, at least on windows. And i don't like it going full screen using this shortkey as it does right now, i would like it to function similar to other text editors, because that's somewhat quite useful feature - it does two operations in one combination. Then again i have no clue if that breaks something on macos. Also on Windows `alt+enter` is mostly used to enter into fullscreen, but i wouldn't mind if `F11` would be used to match browser, sublime and vscode behavior.

Thanks for your explanation regarding speed reading, the thing is, i am selecting the block of text, and then pressing the <Ctrl+k> shortcut, and nothing happens... All other shortcuts seems to be working, but in some cases, for some reason, i couldn't run any actions all, until i have unfocused and focused back into the window. But i couldn't reproduce it now...

**Comment by neauoire** [comment]
It's a very low cost change, and it doesn't really mess with OSX's fullscreen normal behaviours. 
I will try to implement as soon as I'm done with #83.

Is it possible that you were in insert-mode, that locks shortcuts?

**Comment by isRyven** [comment]
Nah, as i see, when you get into insert mode, it shows a hint text on the status panel, with all accessible insert shortcuts, but when i had a problem with making <Ctrl+b> working, it was displaying the open link hint instead, so i suppose i was not in the insert mode. Anyways that just happened once i think, and i can't reproduce that anymore, so i am not entirely sure what was going on.
But anyways back to speed reader, uhm, do you happen to have some video showing what speed reader supposed to look like in action, i mean in the Left. It shows the hint to select the text, if you haven't yet, so i guess the shortcut itself is working, but the reader doesn't do anything at all.

**Comment by neauoire** [comment]
Oh! It's broken on the public build!
Fixing that right away, sorry.

It's not you, it's me.

**Comment by neauoire** [comment]
Implemented, see [preview](https://imgur.com/a/23GMiW4).

Activate with ctrl+shift+enter, for now.

**Comment by isRyven** [comment]
Awesome, thanks!
