### ISSUE TITLE
Cycling through synonyms doesn't return to original word. 

### ISSUE THREAD

**Issue by ryanbugden** [hundredrabbits/Left#91]
Maybe there should be an intuitive way to cancel out of the cycle and keep the original word?

**Comment by neauoire** [comment]
That's a good idea, I'll just always include the original word in the loop :)

**Comment by neauoire** [comment]
That's a good idea! 
I'm not sure how to operate on the edit history tho.

**Comment by neauoire** [comment]
While it does not return to the original word, I've changed the behaviour of the synonym lookup. Could you try this and tell me if that works for you :)

**Comment by pacocoursey** [comment]
Seems like it's back to the problem that long synonym lists don't display some of the words at all (I tried to improve this in #87 by only showing the remaining words). And I'm not sure if this is any easier to return to the original word.

I'll think about a way to avoid changing the history state when selecting a new synonym..

Unrelated, but I think the `Cmd+.` keybind is being overridden by selecting the next marker.

**Comment by neauoire** [comment]
Maybe I would wrap the synonyms into an element, and scroll that element to follow the selected word? I think that'd work. I was thinking of making the console show up on `cmd+shift+i` like the electron apps? 
What do you think?

**Comment by pacocoursey** [comment]
Sorry, I kinda went MIA on this.

Here's the behavior I had in mind -- simply scroll through the list until you get to the end, then repeat from the beginning. In the gif below, the original word is added as the last element of the synonyms (this serves as a way of returning to the original, but takes a while...)

![synonyms](https://user-images.githubusercontent.com/34928425/46637750-db156200-cb1a-11e8-90b4-e0a12bdf17e3.gif)

**Comment by neauoire** [comment]
I don't like that it flickers to much, it's hard to read, it's why I changed it back to highlighting the next word. I had some success making it scroll to the last word when it overflows. I think this is a good behaviour, I just need to clean up the code a bit.

**Comment by pacocoursey** [comment]
Fair enough. Maybe generate an unordered list with each word being a separate `<li>` element (displayed inline, with overflow-y: scroll) and scroll to the appropriate list item?

I can take a shot at it, if you'd like.

**Comment by neauoire** [comment]
That would be perfect, the issue I have with this is fighting the `stats.update()` redraw of the content.

**Comment by neauoire** [comment]
this is very nice, I think it should go in.

**Comment by neauoire** [comment]
Do you think this could be animated?

**Comment by pacocoursey** [comment]
Yes. I spent a long time trying to use [element.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) with the smooth behavior, but the `inline` positioning option didn't seem to work for the horizontal list.

We could manually scroll it smoothly using a loop maybe.

**Comment by pacocoursey** [comment]
I feel very stupid. `scrollIntoView` is fairly new/experimental so it's not included in the version of Chrome shipped with Electron that Left was using. I've upgraded to Electron 3.0.4 and opened a pull request (#96)

**Comment by pacocoursey** [comment]
I believe this can be closed @neauoire

**Comment by neauoire** [comment]
Ah! Yes, definitely.
