### ISSUE TITLE
Monospaced font `input_mono_regular` seems to be missing

### ISSUE THREAD

**Issue by AntonNiklasson** [hundredrabbits/Left#98]
I just downloaded the most recent version, where the font seems to be missing.

The issue might be on [line 3 in main.css](https://github.com/hundredrabbits/Left/blob/master/desktop/sources/links/main.css#L3), I couldn't find any other reference to that font-family.

<img width="849" alt="screenshot 2018-11-14 at 20 05 37" src="https://user-images.githubusercontent.com/785676/48506024-c67a6700-e848-11e8-8ea2-ba8588ec854f.png">

**Comment by neauoire** [comment]
Fixed :) Thanks.
